#development:
#  adapter: mysql2
#  database: kylecovell_development
#  username: root
#  password: root
#  host: localhost
#
#test:
#  adapter: mysql2
#  database: kylecovell_development
#  username: root
#  password: root
#  host: localhost
#
#production:
#  adapter: mysql2
#  database: kylecovell_development
#  username: root
#  password: root
#  host: localhost

development:
  host: 127.0.0.1
  adapter: mysql2
  encoding: utf8
  database: dev-db
  pool: 5
  timeout: 5000

test:
  host: 127.0.0.1
  adapter: mysql2
  encoding: utf8
  database: test-db
  pool: 5
  timeout: 5000

production:
  host: 127.0.0.1
  adapter: mysql2
  encoding: utf8
  database: prod-db
  pool: 5
  timeout: 5000